### ISSUE TITLE
Error when running on Flutter 2.10.3

### ISSUE THREAD

**Issue by RustamG** [anaisbetts/squirrel-flutter#5]
Running `flutter pub run squirrel:installer_windows` on 2.2.3 was successful. But after update to Flutter 2.10.3 it results to an error:
```
Unhandled exception:
FileSystemException: Cannot open file, path = 'c:\users\public\my_project\.dart_tool\pub\bin\nuspec.jinja' (OS Error: No such file or directory, errno = 2)
#0      _File.open.<anonymous closure> (dart:io/file_impl.dart:356:9)
<asynchronous suspension>
#1      main (file:///C:/Users/MyUser/AppData/Local/Pub/Cache/hosted/pub.dartlang.org/squirrel-0.1.0/bin/installer_windows.dart:210:7)
<asynchronous suspension>
pub finished with exit code 255
```

Seems that the installer_windows.dart script is running from the folder other than expected.

@anaisbetts Any thoughts on the fix?

**Comment by anaisbetts** [comment]
https://github.com/anaisbetts/squirrel-flutter/issues/3#issuecomment-1079157085

**Comment by RustamG** [comment]
@anaisbetts How does it look? Would it be possible to publish this update?
